#!/bin/bash

# USES: This scrips will alow you to stop/start portainer based in its execution state
# REQUIRE Change the 'portainer' word in the code with the name or hash of the
# container used for portainer to run.

if [ ! "$(docker ps | grep 'portainer')" ]
then
echo "starting portainer"
docker start portainer
else
echo "stoping portainer"
docker stop portainer
fi
